services:
  # PostgreSQL with PostGIS extension
  postgres:
    image: postgis/postgis:16-3.4
    container_name: yuzu_postgres
    environment:
      POSTGRES_USER: yuzu
      POSTGRES_PASSWORD: yuzu_dev_password
      POSTGRES_DB: yuzu
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=en_US.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yuzu -d yuzu"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # pgAdmin (optional - web UI for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: yuzu_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@yuzu.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
    profiles:
      - tools  # Only starts with: docker compose --profile tools up

volumes:
  postgres_data:
    name: yuzu_postgres_data
  pgadmin_data:
    name: yuzu_pgadmin_data

