services:
  # PostgreSQL with PostGIS extension
  postgres:
    image: postgis/postgis:16-3.4
    container_name: yuzu_postgres
    environment:
      POSTGRES_USER: yuzu
      POSTGRES_PASSWORD: yuzu_dev_password
      POSTGRES_DB: yuzu
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=en_US.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yuzu -d yuzu"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    name: yuzu_postgres_data
